### ISSUE TITLE
Potential bug in forward.cu

### ISSUE THREAD

**Issue by RuijieZhu94** [Zerg-Overmind/diff-gaussian-rasterization#2]
Hi @Zerg-Overmind, thanks for open sourcing this great repo.

In [forward.cu#L391](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/blob/main/cuda_rasterizer/forward.cu#L391), the y coordinate of x_mu seems to be indexed incorrectly.

```
x_mu[calc * H * W * 2 + pix_id] = d.y; 
```

Assuming that top K=20 Gaussians, it seems that it should be changed to the following:

```
x_mu[20 * H * W + calc * H * W + pix_id] = d.y;
```

These are my thoughts at the moment. Please forgive me if I'm mistaken.

**Comment by Zerg-Overmind** [comment]
Sorry for my late reply.
Yes, you are right! Somehow I uploaded a wrong version... also, to my experience, full version as in Eq8 will not perform significantly better than the simplified version as Eq9 in our paper.
Another tip is that, detaching all the tensors related to t_1 and not detaching tensors at t_2 will accelerate the gradient backward and there is no performance decrease.  Just put these notes here for others.
Thanks for pointing out!

**Comment by RuijieZhu94** [comment]
Hi @Zerg-Overmind, thanks for your reply. Now I think the correct code should be like this:
```
x_mu[(calc * 2) * H * W + pix_id] = d.x;
x_mu[(calc * 2 + 1) * H * W + pix_id] = d.y;
```
Because I found that the dimension of x_mu is Kx2xHxW. Please tell me if I'm wrong.

**Comment by Zerg-Overmind** [comment]
Hi @RuijieZhu94 , I think both are ok as long as you do the right reshape operation in pytorch :)

**Comment by RuijieZhu94** [comment]
Hi @Zerg-Overmind, I have to remind you again that the current version of the code is still wrong.

In [forward.cu#L390](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/blob/main/cuda_rasterizer/forward.cu#L390), it should be 
```
x_mu[(calc * 2) * H * W + pix_id] = d.x;
```
if x_mu is defined as K x 2 x H x W.

**Comment by Zerg-Overmind** [comment]
Thank you so much for pointing it out. Just fixed it!

**Comment by Zerg-Overmind** [comment]
Sorry for my multiple local versions which cause the conflicts. Just label the issue for others. Thanks again!

**Comment by mateosss** [comment]
> full version as in Eq8 will not perform significantly better than the simplified version as Eq9 in our paper.

@Zerg-Overmind That is surprising to hear but I guess it makes sense if you have very small gaussians. Have you tried it on a setting with bigger gaussians? i.e., covering more than one pixel of the input images. Or do you have any other insight into why this might be the case?

**Comment by Zerg-Overmind** [comment]
Hi @mateosss, that's right, because most 3D Gaussians are very small after optimization with high resolutional image rendering, which makes the performance gain from Eq8 similar to the one with Eq9.

**Comment by lizhihao6** [comment]
Hi @Zerg-Overmind, if I’m not mistaken, it seems that the gradient of `grad_x_mu` is not being applied to the mean of the Gaussian point (`mu`) ?
